version: '3'
services:
  laravel_web:
    build: ./laravel_web
    image: laravel_web
    depends_on:
      - "laravel_db"
    hostname: "sf3"
    container_name: "laravel_web"
    ports:
      - 8100:80   #apache
    volumes:
      - "../:/var/www/html"
      - "~/.composer:/var/www/.composer"
      - ./laravel_web/zshrc.dist:/var/www/.zshrc:ro
      - ./data/apache/logs:/var/log/apache2
    links:
      - laravel_db
    env_file:
      - docker-env
    networks:
      - laravel_net

  #mysql
  laravel_db:
    image: mariadb:10.3
    container_name: "laravel_db"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/sql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf
    networks:
      - laravel_net

  #phpmyadmin
  laravel_pma:
    image: phpmyadmin/phpmyadmin
    container_name: "laravel_pma"
    links:
      - laravel_db
    depends_on:
      - "laravel_db"
    ports:
      - 8081:80
    #        restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=laravel_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - laravel_net

networks:
  laravel_net: